### ISSUE TITLE
UART1 Window Multi-Character Strings

### ISSUE THREAD

**Issue by Tuxprogrammer** [thirtythreeforty/bullycpp#25] opened 2017-03-29 22:35 UTC
The UART data transfer window cannot send multiple characters at once in the latest revision. Also, you cannot paste strings into the UART data transfer window.

**Comment by thirtythreeforty** [comment] 2017-03-30 15:07
Duplicate of #22?  This has been fixed in `master` and will be released as soon as I get some time.

**Comment by thirtythreeforty** [comment] 2017-03-31 19:27
I'm gonna close this as a duplicate but if you mean something different feel free to reopen!

**Closed as completed by thirtythreeforty** 2017-03-31 19:27 UTC
Labels: duplicate
